[workspace]
members = [
    "crates/keel-core",
    "crates/keel-cli",
    "crates/speccy",
    "crates/spoke-auth",
    "crates/txt-scene"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["keel contributors"]
license = "MIT"
repository = "https://github.com/rupurt/keel"
homepage = "https://github.com/rupurt/keel"

[workspace.dependencies]
keel-core = { path = "crates/keel-core" }
speccy = { path = "crates/speccy" }
spoke-auth = { path = "crates/spoke-auth" }
txt-scene = { path = "crates/txt-scene" }
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
